version: '3.8'

services:
  json-processor:
    build: .
    container_name: json-processor-api
    ports:
      - "5000:5000"
    volumes:
      - ./generated_questions:/app/generated_questions:ro  # Input dosyaları (read-only)
      - ./gpt_generated_questions:/app/gpt_generated_questions  # Output dosyaları
      - ./logs:/app/logs  # Log dosyaları
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"